name: Trigger Fixture Regeneration

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types:
      - labeled

jobs:
  regenerate_fixtures:
    if: github.event.label.name == 'regenerate-fixtures'
    uses: codecrafters-io/tester-utils/.github/workflows/fixtures.yml@andy/update-fixture-permisions
    with:
      tester_repo: grep-tester
    secrets: inherit