name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.x

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Set up Ripgrep with PCRE2
        run: |
          curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.0.2/ripgrep_14.0.2-1_amd64.deb
          sudo dpkg -i ripgrep_14.0.2-1_amd64.deb

      - run: make test
