name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.x

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: echo "123" | grep -E "\d"
      - run: echo "123" | ./internal/test_helpers/pass_all/your_grep.sh -E "\d"
      - run: make test
