name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.x

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Set up Busybox
        run: |
          sudo apt-get update
          sudo apt install -y busybox

      - run: busybox sh
      - run: echo "123" | grep -e "\d"
      - run: echo "123" | grep "\d"
      - run: echo "123" | grep -E "\d"
      - run: make test
